### ISSUE TITLE
Implement "expected to fail" for individual assertions

### ISSUE THREAD

**Issue by waywardmonkeys** [dylan-lang/testworks#81]
Right now, the support for expected failures is on an entire test definition.

It would be useful to be able to say that certain asserts / checks are expected to fail rather than the entire test.

This comes up in some tests that I have where a number of test cases don't work yet but I want to make sure that each of them is either failing or succeeding as expected. I don't want to create a separate test for each check that should fail.

**Comment by cgay** [comment]
Two thoughts on this...

1. I suspect this is rare enough that it's not worth the added implementation complexity just to avoid making a separate test, but...

2. Summary results are confusing when an individual assertion fails but all tests pass due to the test being marked as expected to fail:

```
...
Running test test-included-in-suite-multiple-times:
  1 = 2: [1 and 2 are not =.]
   FAILED AS EXPECTED in 0.000446s and 10KiB
Running test test-current-test: PASSED in 0.000019s and 744B
Running test test-that-not-implemented-plus-passed-is-passed: PASSED in 0.000070s and 1KiB
Completed suite testworks-run: PASSED in 0.023196s

testworks-run PASSED in 0.023196 seconds:
  Ran 7 suites: 7 passed (100.00000%)
  Ran 45 tests: 45 passed (100.00000%)
  Ran 2 benchmarks: 2 passed (100.00000%)
  Ran 1190 checks: 1189 passed (99.915960%), 1 failed, 0 skipped, 0 not implemented, 0 crashed
```

Note that 1 check failed but all tests passed.  So there's already some additional work needed.  I suggest this output for the above results:
```
testworks-run PASSED in 23ms:
  Ran 7 suites: 1 expected failure
  Ran 45 tests: 1 expected failure
  Ran 2 benchmarks: 0 failed
  Ran 1190 checks: 1 failed
```
Everything else is noise.

**Comment by cgay** [comment]
What does it mean when an assertion is expected to fail and the test is expected to pass?

**Comment by cgay** [comment]
Changed my mind on this because it turns out that treating assertions differently in this respect makes it necessary to add hacks to the reporting output, like keeping track of the test containing the assertion so that we can know whether the assertion can be marked as expected to fail.

(For simplicity, I'd be fine with not tracking / reporting the individual check counts at all, but at this point it's probably less work to implement expected to fail for individual assertions.)

**Comment by cgay** [comment]
Sigh.  Another question is, what does it mean when a test is marked as expected to fail and an assertion fails but is *not* marked as expected to fail?  Do we essentially have to duplicate the `expected-to-fail-reason:` in the assertion and the test?

Nope, not going to do this.
